Task 1 Simple Calculations Formulas
PycJIaH/MathTasks pull request #3
Opened 2023-10-15 20:38 UTC by PycJIaH

- Added tests to check formulas

2023-10-15 21:07 UTC, unixshaman requested changes

2023-10-15 21:07 UTC, unixshaman commented on MathTasks/Task_1_SimpleCalculationsFormulas.cs
> +            Console.WriteLine(MathEquation1(double.Parse(consoleInput)));
Если в consoleInput придет строка, то это рухнет в этом месте. Не хорошо, чтобы программа рушилась.

2023-10-15 21:07 UTC, unixshaman commented on MathTasksTests/Task_1_SimpleCalculationsFormulas_UnitTests.cs
> +            Assert.AreEqual(-0.693307715624919, Task_1_SimpleCalculationsFormulas.MathEquation3(0.5));
Кажется, этот неймспейс стоит добавить в импорт.

2023-10-15 21:07 UTC, unixshaman commented on MathTasksTests/Task_1_SimpleCalculationsFormulas_UnitTests.cs
> +        public void MathEquation1_Tests(double act, double exp)
А окончание s в слове Tests автоматически проставилось? А то вроде бы один тест, не понятно, почему во множественном числе.

2023-10-15 22:59 UTC, PycJIaH commented on MathTasks/Task_1_SimpleCalculationsFormulas.cs
> +            Console.WriteLine(MathEquation1(double.Parse(consoleInput)));
Обернул в TryCatch

2023-10-17 14:19 UTC, unixshaman requested changes

2023-10-17 14:19 UTC, unixshaman commented on MathTasks/Task_1_SimpleCalculationsFormulas.cs
> +        try
Нельзя оборачивать кучу кода в try catch, особенно, если в catch обработка только для конкретной ситуации. В данном случае - надо обернуть в try catch только ввод от пользователя, и после этого выйти из программы используя return.

2023-10-18 05:22 UTC, PycJIaH commented on MathTasks/Task_1_SimpleCalculationsFormulas.cs
> +        try
Я не понял что именно ты хочешь чтобы я обернул:
Если я делаю return в try catch то мне выдаёт ошибку что у меня Main в void
Если я создаю `string? consoleInput = null` до try catch, то программа try catch тупо не ловит ошибку, просто ломается программа

2023-12-12 20:31 UTC, PycJIaH commented on MathTasks/Task_1_SimpleCalculationsFormulas.cs
> +        try
Устранено

2024-01-07 03:47 UTC, merged